# Generated by Django 4.2.9 on 2024-03-05 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymFindr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city_location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
    ]
